/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CmButton: typeof import('./src/components/common/CmButton.vue')['default']
    CmCheckbox: typeof import('./src/components/common/CmCheckbox.vue')['default']
    CmInput: typeof import('./src/components/common/CmInput.vue')['default']
    CmRadio: typeof import('./src/components/common/CmRadio.vue')['default']
    CmSelect: typeof import('./src/components/common/CmSelect.vue')['default']
    CmTest: typeof import('./src/components/common/CmTest.vue')['default']
    CmTextarea: typeof import('./src/components/common/CmTextarea.vue')['default']
    DialogComponent: typeof import('./src/components/dialog/components/DialogComponent.vue')['default']
    Guide: typeof import('./src/layout/guide/index.vue')['default']
    GuideColor: typeof import('./src/layout/guide/GuideColor.vue')['default']
    GuideLayout: typeof import('./src/layout/guide/GuideLayout.vue')['default']
    GuideMenu: typeof import('./src/layout/guide/GuideMenu.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ModalComponent: typeof import('./src/components/modal/components/ModalComponent.vue')['default']
    ModalContainer: typeof import('./src/components/modal/components/ModalContainer.vue')['default']
    Notification: typeof import('./src/components/notification/components/Notification.vue')['default']
    NotificationComponent: typeof import('./src/components/notification/components/NotificationComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SamplePopup: typeof import('./src/components/modal/SamplePopup.vue')['default']
    SamplePopup2: typeof import('./src/components/modal/SamplePopup2.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UseValidation: typeof import('./src/components/useValidation.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
